const questionsData = {
    themes: {
        "Boca Juniors": [
            { text: "¿En qué año fue fundado Boca Juniors?", options: ["1905", "1910", "1920"], correct: 0 },
            { text: "¿Cuál es el estadio de Boca Juniors conocido popularmente?", options: ["El Monumental", "La Bombonera", "El Cilindro"], correct: 1 },
            { text: "¿Cuántas Copas Libertadores ha ganado Boca Juniors hasta 2020?", options: ["4", "6", "8"], correct: 1 },
            { text: "¿Quién es el máximo goleador histórico de Boca Juniors?", options: ["Martín Palermo", "Carlos Tevez", "Diego Maradona"], correct: 0 },
            { text: "¿Qué jugador de Boca Juniors es conocido como 'El Loco'?", options: ["Juan Román Riquelme", "Martín Palermo", "Hugo Gatti"], correct: 2 },
            { text: "¿En qué barrio de Buenos Aires está ubicado el estadio de Boca Juniors?", options: ["Palermo", "La Boca", "Recoleta"], correct: 1 },
            { text: "¿Quién es el entrenador más exitoso en la historia de Boca Juniors?", options: ["Alfio Basile", "Carlos Bianchi", "Miguel Ángel Russo"], correct: 1 },
            { text: "¿Qué jugador famoso de Boca Juniors también jugó para el FC Barcelona?", options: ["Lionel Messi", "Carlos Tevez", "Diego Maradona"], correct: 2 },
            { text: "¿Qué rival de Boca Juniors es conocido como 'El Superclásico'?", options: ["Racing Club", "San Lorenzo", "River Plate"], correct: 2 },
            { text: "¿Qué color predominante tiene la camiseta de Boca Juniors?", options: ["Azul y oro", "Rojo y blanco", "Negro y amarillo"], correct: 0 }
        ],
        "River Plate": [
            { text: "¿En qué año fue fundado River Plate?", options: ["1901", "1905", "1910"], correct: 0 },
            { text: "¿Cuál es el apodo de River Plate?", options: ["El Rojo", "El Millonario", "El Fortín"], correct: 1 },
            { text: "¿Cuántas Copas Libertadores ha ganado River Plate hasta 2020?", options: ["3", "4", "5"], correct: 1 },
            { text: "¿Quién es el máximo goleador histórico de River Plate?", options: ["Norberto Alonso", "Enzo Francescoli", "Ángel Labruna"], correct: 2 },
            { text: "¿Cuál es el nombre del estadio de River Plate?", options: ["Estadio Monumental", "La Bombonera", "El Gasómetro"], correct: 0 },
            { text: "¿Qué jugador de River Plate es conocido como 'El Príncipe'?", options: ["Enzo Francescoli", "Daniel Passarella", "Ariel Ortega"], correct: 0 },
            { text: "¿Qué entrenador llevó a River Plate a ganar la Copa Libertadores en 2015?", options: ["Ramón Díaz", "Marcelo Gallardo", "Héctor Veira"], correct: 1 },
            { text: "¿Quién fue el primer entrenador de River Plate?", options: ["Renato Cesarini", "José María Minella", "Carlos Peucelle"], correct: 2 },
            { text: "¿Qué color predominante tiene la camiseta de River Plate?", options: ["Rojo y blanco", "Azul y oro", "Verde y negro"], correct: 0 },
            { text: "¿Qué jugador de River Plate fue apodado 'El Burrito'?", options: ["Pablo Aimar", "Ariel Ortega", "Javier Saviola"], correct: 1 }
        ],
        "Independiente": [
            { text: "¿En qué año fue fundado Independiente?", options: ["1904", "1905", "1906"], correct: 1 },
            { text: "¿Cuál es el apodo de Independiente?", options: ["El Ciclón", "El Rojo", "La Academia"], correct: 1 },
            { text: "¿Cuántas Copas Libertadores ha ganado Independiente hasta 2020?", options: ["5", "6", "7"], correct: 2 },
            { text: "¿Quién es el máximo goleador histórico de Independiente?", options: ["Arsenio Erico", "Ricardo Bochini", "Sergio Agüero"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Independiente?", options: ["Estadio Libertadores de América", "El Monumental", "La Bombonera"], correct: 0 },
            { text: "¿Qué jugador de Independiente es conocido como 'El Bocha'?", options: ["Diego Forlán", "Ricardo Bochini", "Gabriel Milito"], correct: 1 },
            { text: "¿Qué entrenador llevó a Independiente a ganar su primera Copa Libertadores?", options: ["Osvaldo Zubeldía", "José Pastoriza", "Manuel Giúdice"], correct: 2 },
            { text: "¿Quién fue el primer entrenador de Independiente?", options: ["Renato Cesarini", "José María Minella", "Carlos Peucelle"], correct: 2 },
            { text: "¿Qué color predominante tiene la camiseta de Independiente?", options: ["Rojo", "Azul", "Blanco"], correct: 0 },
            { text: "¿Qué jugador de Independiente fue apodado 'Kun'?", options: ["Diego Forlán", "Sergio Agüero", "Gabriel Milito"], correct: 1 }
        ],
        "Racing Club": [
            { text: "¿En qué año fue fundado Racing Club?", options: ["1903", "1905", "1908"], correct: 2 },
            { text: "¿Cuál es el apodo de Racing Club?", options: ["El Globo", "La Academia", "El Granate"], correct: 1 },
            { text: "¿Cuántas Copas Libertadores ha ganado Racing Club hasta 2020?", options: ["1", "2", "3"], correct: 0 },
            { text: "¿Quién es el máximo goleador histórico de Racing Club?", options: ["Lisandro López", "Diego Milito", "Alberto Ohaco"], correct: 2 },
            { text: "¿Cuál es el nombre del estadio de Racing Club?", options: ["El Cilindro", "La Bombonera", "El Monumental"], correct: 0 },
            { text: "¿Qué jugador de Racing Club es conocido como 'El Príncipe'?", options: ["Diego Milito", "Gabriel Batistuta", "Ricardo Bochini"], correct: 0 },
            { text: "¿Qué entrenador llevó a Racing Club a ganar la Superliga Argentina en 2019?", options: ["Eduardo Coudet", "Diego Cocca", "Alfio Basile"], correct: 0 },
            { text: "¿Quién fue el primer entrenador de Racing Club?", options: ["Juan José Pizzuti", "Pedro Dellacha", "Alfio Basile"], correct: 0 },
            { text: "¿Qué color predominante tiene la camiseta de Racing Club?", options: ["Celeste y blanco", "Rojo y blanco", "Azul y amarillo"], correct: 0 },
            { text: "¿Qué jugador de Racing Club fue apodado 'Licha'?", options: ["Lisandro López", "Diego Milito", "Gabriel Hauche"], correct: 0 }
        ],"Aldosivi": [
            { text: "¿En qué ciudad de Argentina se encuentra el equipo Aldosivi?", options: ["Mar del Plata", "La Plata", "Buenos Aires"], correct: 0 },
            { text: "¿Cuál es el apodo del equipo Aldosivi?", options: ["El Tiburón", "El Canalla", "El Bicho"], correct: 0 },
            { text: "¿En qué año se fundó el Club Aldosivi?", options: ["1913", "1923", "1933"], correct: 1 },
            { text: "¿Cuál es el nombre del estadio de Aldosivi?", options: ["José María Minella", "Diego Armando Maradona", "Juan Carmelo Zerillo"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Aldosivi?", options: ["Verde y amarillo", "Rojo y blanco", "Azul y oro"], correct: 0 },
            { text: "¿En qué año Aldosivi ascendió a la Primera División por primera vez en su historia?", options: ["2010", "2014", "2018"], correct: 1 },
            { text: "¿Cuál fue el logro más importante de Aldosivi en su historia?", options: ["Campeón de la Copa Argentina", "Ascenso a Primera División", "Clasificación a la Copa Sudamericana"], correct: 1 },
            { text: "¿Contra qué equipo Aldosivi disputa el clásico marplatense?", options: ["Unión", "Alvarado", "Kimberley"], correct: 1 },
            { text: "¿Qué ex-jugador de la selección argentina es ídolo en Aldosivi?", options: ["Juan Román Riquelme", "Fernando Gago", "Walter Perazzo"], correct: 2 },
            { text: "¿En qué división juega Aldosivi en el año 2023?", options: ["Primera B Nacional", "Primera División", "Torneo Federal A"], correct: 0 }
        ],
        "Argentinos Juniors": [
            { text: "¿En qué barrio de Buenos Aires fue fundado Argentinos Juniors?", options: ["La Paternal", "Villa Crespo", "Caballito"], correct: 0 },
            { text: "¿Cuál es el apodo de Argentinos Juniors?", options: ["El Bicho", "El Rojo", "El Fortín"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Argentinos Juniors?", options: ["Estadio Diego Armando Maradona", "Estadio José Amalfitani", "Estadio Libertadores de América"], correct: 0 },
            { text: "¿Cuántas Copas Libertadores ha ganado Argentinos Juniors?", options: ["1", "2", "3"], correct: 0 },
            { text: "¿Qué jugador legendario de la selección argentina debutó en Argentinos Juniors?", options: ["Diego Maradona", "Lionel Messi", "Gabriel Batistuta"], correct: 0 },
            { text: "¿Qué jugador es conocido como 'El Pocho' en Argentinos Juniors?", options: ["Juan Román Riquelme", "Ezequiel Lavezzi", "José Pekerman"], correct: 1 },
            { text: "¿Qué año Argentinos Juniors se consagró campeón de la Copa Libertadores?", options: ["1980", "1985", "1990"], correct: 1 },
            { text: "¿Cuál es el color predominante de la camiseta de Argentinos Juniors?", options: ["Rojo y blanco", "Verde y negro", "Azul y rojo"], correct: 0 },
            { text: "¿En qué año se fundó Argentinos Juniors?", options: ["1900", "1904", "1908"], correct: 1 },
            { text: "¿Quién fue el técnico campeón de la Copa Libertadores con Argentinos Juniors?", options: ["Jorge Solari", "Osvaldo Sosa", "José Yudica"], correct: 2 }
        ],
        "Atlético Tucumán": [
            { text: "¿En qué provincia de Argentina se encuentra el equipo Atlético Tucumán?", options: ["Tucumán", "Salta", "Jujuy"], correct: 0 },
            { text: "¿Cuál es el apodo de Atlético Tucumán?", options: ["El Decano", "El Ciruja", "El Santo"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Atlético Tucumán?", options: ["Celeste y blanco", "Blanco y azul", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Atlético Tucumán?", options: ["Estadio Monumental José Fierro", "Estadio 23 de Agosto", "Estadio Padre Ernesto Martearena"], correct: 0 },
            { text: "¿En qué año se fundó Atlético Tucumán?", options: ["1902", "1905", "1910"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Atlético Tucumán?", options: ["San Martín de Tucumán", "Central Córdoba", "Talleres"], correct: 0 },
            { text: "¿Cuál fue el mayor logro internacional de Atlético Tucumán?", options: ["Llegar a la final de la Copa Sudamericana", "Llegar a cuartos de final de la Copa Libertadores", "Ganar la Copa Conmebol"], correct: 1 },
            { text: "¿Qué jugador histórico de la selección argentina jugó en Atlético Tucumán?", options: ["Sergio Agüero", "Ricardo Bochini", "Noel Leal"], correct: 2 },
            { text: "¿Quién es el máximo ídolo del club?", options: ["Luis Miguel Rodríguez", "Cristian Menéndez", "Juan Manuel Azconzábal"], correct: 0 },
            { text: "¿Cuál es el nombre del torneo que ganó Atlético Tucumán en 2009, logrando el ascenso a la Primera División?", options: ["Nacional B", "Torneo Argentino A", "Copa Argentina"], correct: 0 }
        ],
        "Banfield": [
            { text: "¿En qué localidad de la provincia de Buenos Aires se encuentra Banfield?", options: ["Lomas de Zamora", "Avellaneda", "Lanús"], correct: 0 },
            { text: "¿Cuál es el apodo de Banfield?", options: ["El Taladro", "El Granate", "El Rojo"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Banfield?", options: ["Verde y blanco", "Rojo y negro", "Azul y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Banfield?", options: ["Estadio Florencio Sola", "Estadio Ciudad de Lanús", "Estadio Néstor Díaz Pérez"], correct: 0 },
            { text: "¿En qué año Banfield fue campeón de la Primera División por primera vez?", options: ["2005", "2009", "2013"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Banfield?", options: ["Lanús", "Temperley", "Los Andes"], correct: 0 },
            { text: "¿Qué jugador famoso de Banfield es conocido como 'El Garca'?", options: ["Walter Erviti", "Cristian Lucchetti", "José Sand"], correct: 0 },
            { text: "¿Quién fue el entrenador que llevó a Banfield a ser campeón en 2009?", options: ["Julio César Falcioni", "Matías Almeyda", "Gustavo Alfaro"], correct: 0 },
            { text: "¿Qué jugador surgido de las inferiores de Banfield jugó en la selección argentina?", options: ["Darío Cvitanich", "Javier Zanetti", "James Rodríguez"], correct: 0 },
            { text: "¿En qué año se fundó el Club Banfield?", options: ["1890", "1896", "1900"], correct: 1 }
        ],
        "Barracas Central": [
            { text: "¿En qué barrio de Buenos Aires se encuentra Barracas Central?", options: ["Barracas", "La Boca", "Parque Patricios"], correct: 0 },
            { text: "¿Cuál es el apodo de Barracas Central?", options: ["El Guapo", "El Funebrero", "El Cervecero"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Barracas Central?", options: ["Rojo y blanco", "Azul y rojo", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Barracas Central?", options: ["Estadio Claudio 'Chiqui' Tapia", "Estadio Islas Malvinas", "Estadio Don León Kolbowski"], correct: 0 },
            { text: "¿En qué año se fundó Barracas Central?", options: ["1913", "1915", "1920"], correct: 1 },
            { text: "¿Cuál es el clásico rival de Barracas Central?", options: ["Deportivo Riestra", "Nueva Chicago", "Excursionistas"], correct: 0 },
            { text: "¿Qué dirigente del fútbol argentino está estrechamente relacionado con Barracas Central?", options: ["Julio Grondona", "Daniel Angelici", "Claudio Tapia"], correct: 2 },
            { text: "¿En qué año Barracas Central logró su primer ascenso a la Primera División?", options: ["2015", "2020", "2021"], correct: 2 },
            { text: "¿Cuál es el máximo logro de Barracas Central en su historia?", options: ["Campeón de la Primera B Nacional", "Ascenso a Primera División", "Ganar la Copa Argentina"], correct: 0 },
            { text: "¿En qué año ascendió Barracas Central por primera vez en su historia a la máxima categoría del fútbol argentino?", options: ["2020", "2021", "2022"], correct: 1 }
        ],
        "Belgrano": [
            { text: "¿En qué provincia de Argentina se encuentra el equipo Belgrano?", options: ["Santa Fe", "Córdoba", "Buenos Aires"], correct: 1 },
            { text: "¿Cuál es el apodo de Belgrano?", options: ["El Pirata", "El Matador", "El Albiazul"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Belgrano?", options: ["Celeste", "Azul y blanco", "Rojo y negro"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Belgrano?", options: ["Estadio Julio César Villagra", "Estadio Mario Alberto Kempes", "Estadio Juan Carmelo Zerillo"], correct: 0 },
            { text: "¿Cuál es el clásico rival de Belgrano?", options: ["Talleres", "Instituto", "Rosario Central"], correct: 0 },
            { text: "¿En qué año Belgrano descendió a River Plate a la B Nacional?", options: ["2005", "2011", "2015"], correct: 1 },
            { text: "¿Qué jugador es el máximo ídolo en la historia de Belgrano?", options: ["Juan Carlos Olave", "Mario Bolatti", "Lucas Bernardi"], correct: 0 },
            { text: "¿En qué año se fundó el Club Belgrano?", options: ["1901", "1905", "1910"], correct: 0 },
            { text: "¿Qué otro equipo de Córdoba es el rival de Belgrano?", options: ["Instituto", "Racing de Córdoba", "Talleres"], correct: 2 },
            { text: "¿En qué año Belgrano volvió a ascender a Primera División?", options: ["2018", "2021", "2022"], correct: 2 }
        ],
        "Central Córdoba (Santiago del Estero)": [
            { text: "¿De qué provincia de Argentina es el equipo Central Córdoba?", options: ["Tucumán", "Santiago del Estero", "La Rioja"], correct: 1 },
            { text: "¿Cuál es el apodo de Central Córdoba?", options: ["El Ferroviario", "El Decano", "El Santo"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Central Córdoba?", options: ["Negro y blanco", "Rojo y blanco", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Central Córdoba?", options: ["Estadio Alfredo Terrera", "Estadio Único Madre de Ciudades", "Estadio Ciudad de La Banda"], correct: 0 },
            { text: "¿En qué año se fundó Central Córdoba?", options: ["1919", "1923", "1930"], correct: 0 },
            { text: "¿Contra qué equipo es el clásico de Central Córdoba?", options: ["Mitre de Santiago del Estero", "Talleres", "San Martín de Tucumán"], correct: 0 },
            { text: "¿Cuál fue el mayor logro en la historia de Central Córdoba?", options: ["Llegar a la final de la Copa Argentina", "Ascenso a la Primera División", "Ganar la Primera B Nacional"], correct: 0 },
            { text: "¿En qué año ascendió por primera vez a la Primera División?", options: ["1967", "1971", "1982"], correct: 0 },
            { text: "¿Qué jugador histórico del fútbol argentino jugó en Central Córdoba?", options: ["Lionel Messi", "Carlos Tevez", "Renato Cesarini"], correct: 2 },
            { text: "¿Qué entrenador llevó a Central Córdoba a la final de la Copa Argentina?", options: ["Gustavo Coleoni", "Sergio Rondina", "Alfredo Berti"], correct: 0 }
        ],
        "Defensa y Justicia": [
            { text: "¿En qué localidad de la provincia de Buenos Aires se encuentra Defensa y Justicia?", options: ["Florencio Varela", "Berazategui", "Quilmes"], correct: 0 },
            { text: "¿Cuál es el apodo de Defensa y Justicia?", options: ["El Halcón de Varela", "El Verde", "El Cervecero"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Defensa y Justicia?", options: ["Verde y amarillo", "Azul y blanco", "Rojo y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Defensa y Justicia?", options: ["Estadio Norberto 'Tito' Tomaghello", "Estadio Juan Carmelo Zerillo", "Estadio José Amalfitani"], correct: 0 },
            { text: "¿En qué año se fundó Defensa y Justicia?", options: ["1930", "1935", "1940"], correct: 1 },
            { text: "¿Qué entrenador llevó a Defensa y Justicia a ganar su primer título internacional?", options: ["Sebastián Beccacece", "Hernán Crespo", "Ariel Holan"], correct: 1 },
            { text: "¿Qué título internacional ganó Defensa y Justicia en 2020?", options: ["Copa Libertadores", "Copa Sudamericana", "Recopa Sudamericana"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Defensa y Justicia?", options: ["Arsenal de Sarandí", "Quilmes", "Banfield"], correct: 0 },
            { text: "¿Qué jugador surgido de Defensa y Justicia jugó en el fútbol europeo?", options: ["Juan Manuel Salgueiro", "Matías Delgado", "Ezequiel Unsain"], correct: 2 },
            { text: "¿En qué año logró Defensa y Justicia el ascenso a la Primera División?", options: ["2010", "2014", "2018"], correct: 1 }
        ],
        "Deportivo Riestra": [
            { text: "¿En qué barrio de Buenos Aires se encuentra Deportivo Riestra?", options: ["Barracas", "Nueva Pompeya", "La Boca"], correct: 1 },
            { text: "¿Cuál es el apodo de Deportivo Riestra?", options: ["El Malevo", "El Guapo", "El Funebrero"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Deportivo Riestra?", options: ["Blanco y negro", "Azul y rojo", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Deportivo Riestra?", options: ["Estadio Guillermo Laza", "Estadio Islas Malvinas", "Estadio Don León Kolbowski"], correct: 0 },
            { text: "¿En qué año se fundó Deportivo Riestra?", options: ["1925", "1931", "1940"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Deportivo Riestra?", options: ["Comunicaciones", "Sacachispas", "Barracas Central"], correct: 1 },
            { text: "¿Qué empresa de indumentaria deportiva está relacionada con Deportivo Riestra?", options: ["Adidas", "Nike", "Adidas"], correct: 0 },
            { text: "¿En qué año Deportivo Riestra ascendió a la Primera División por primera vez?", options: ["2018", "2020", "2023"], correct: 2 },
            { text: "¿Quién es el presidente de Deportivo Riestra?", options: ["Claudio Tapia", "Guillermo Laza", "Víctor Stinfale"], correct: 2 },
            { text: "¿Qué jugador es el máximo ídolo del club?", options: ["Gustavo Fernández", "Jonathan Herrera", "Walter Sanfilippo"], correct: 1 }
        ],
        "Estudiantes de La Plata": [
            { text: "¿En qué ciudad de Argentina se encuentra el equipo Estudiantes de La Plata?", options: ["La Plata", "Buenos Aires", "Rosario"], correct: 0 },
            { text: "¿Cuál es el apodo de Estudiantes de La Plata?", options: ["El Pincha", "El Lobo", "El Matador"], correct: 0 },
            { text: "¿Cuántas Copas Libertadores ha ganado Estudiantes de La Plata?", options: ["3", "4", "5"], correct: 1 },
            { text: "¿Cuál es el nombre del estadio de Estudiantes de La Plata?", options: ["Estadio UNO Jorge Luis Hirschi", "Estadio Juan Carmelo Zerillo", "Estadio Ciudad de La Plata"], correct: 0 },
            { text: "¿En qué año se fundó Estudiantes de La Plata?", options: ["1905", "1910", "1915"], correct: 0 },
            { text: "¿Qué jugador es el máximo ídolo en la historia de Estudiantes de La Plata?", options: ["Juan Sebastián Verón", "Juan Román Riquelme", "Ricardo Bochini"], correct: 0 },
            { text: "¿Qué entrenador llevó a Estudiantes de La Plata a ganar la Copa Libertadores en 2009?", options: ["Alejandro Sabella", "Diego Simeone", "Eduardo Berizzo"], correct: 0 },
            { text: "¿Quién es el clásico rival de Estudiantes de La Plata?", options: ["Gimnasia y Esgrima de La Plata", "Boca Juniors", "Independiente"], correct: 0 },
            { text: "¿Qué jugador es conocido como 'El Gato' en Estudiantes de La Plata?", options: ["Mariano Andújar", "Ernesto Farias", "Juan Sebastián Verón"], correct: 0 },
            { text: "¿En qué año Estudiantes de La Plata ganó la Copa Intercontinental?", options: ["1968", "1970", "1982"], correct: 0 }
        ],
        "Gimnasia y Esgrima de La Plata": [
            { text: "¿En qué ciudad de Argentina se encuentra el equipo Gimnasia y Esgrima de La Plata?", options: ["La Plata", "Buenos Aires", "Mar del Plata"], correct: 0 },
            { text: "¿Cuál es el apodo de Gimnasia y Esgrima de La Plata?", options: ["El Lobo", "El Pincha", "El Decano"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Gimnasia y Esgrima de La Plata?", options: ["Blanco y azul", "Verde y blanco", "Rojo y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Gimnasia y Esgrima de La Plata?", options: ["Estadio Juan Carmelo Zerillo", "Estadio Ciudad de La Plata", "Estadio Único Diego Armando Maradona"], correct: 0 },
            { text: "¿En qué año se fundó Gimnasia y Esgrima de La Plata?", options: ["1887", "1900", "1910"], correct: 0 },
            { text: "¿Qué club es el clásico rival de Gimnasia y Esgrima de La Plata?", options: ["Estudiantes de La Plata", "Vélez Sarsfield", "Lanús"], correct: 0 },
            { text: "¿Qué jugador histórico de la selección argentina fue entrenador de Gimnasia?", options: ["Lionel Messi", "Diego Maradona", "Gabriel Batistuta"], correct: 1 },
            { text: "¿Cuál fue el mayor logro en la historia de Gimnasia?", options: ["Ganar la Copa Centenario", "Ascenso a la Primera División", "Final de la Copa Argentina"], correct: 0 },
            { text: "¿Qué jugador de Gimnasia es conocido como 'El Pitu'?", options: ["Guillermo Barros Schelotto", "Gastón Sessa", "Pablo Vegetti"], correct: 1 },
            { text: "¿En qué año Gimnasia y Esgrima de La Plata ganó el título de la Copa Centenario?", options: ["1993", "1994", "1995"], correct: 1 }
        ],
        "Godoy Cruz": [
            { text: "¿En qué provincia de Argentina se encuentra el equipo Godoy Cruz?", options: ["Mendoza", "San Juan", "San Luis"], correct: 0 },
            { text: "¿Cuál es el apodo de Godoy Cruz?", options: ["El Tomba", "El Bodeguero", "El Expreso"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Godoy Cruz?", options: ["Blanco y azul", "Rojo y blanco", "Azul y negro"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Godoy Cruz?", options: ["Estadio Malvinas Argentinas", "Estadio Feliciano Gambarte", "Estadio Presbítero Bartolomé Grella"], correct: 0 },
            { text: "¿En qué año se fundó Godoy Cruz?", options: ["1919", "1921", "1930"], correct: 0 },
            { text: "¿Qué club es el clásico rival de Godoy Cruz?", options: ["Independiente Rivadavia", "Gimnasia y Esgrima de Mendoza", "San Martín de Mendoza"], correct: 0 },
            { text: "¿Cuál fue el mayor logro de Godoy Cruz en su historia?", options: ["Semifinales de la Copa Libertadores", "Ascenso a Primera División", "Cuartos de final de la Copa Sudamericana"], correct: 1 },
            { text: "¿Qué jugador de Godoy Cruz es conocido como 'El Morro'?", options: ["Santiago García", "Jaime Ayoví", "Mauro Óbolo"], correct: 0 },
            { text: "¿En qué año Godoy Cruz ascendió por primera vez a Primera División?", options: ["2004", "2006", "2010"], correct: 1 },
            { text: "¿Qué entrenador es considerado un ídolo en Godoy Cruz?", options: ["Omar Asad", "Jorge Almirón", "Mauricio Larriera"], correct: 0 }
        ],
        "Huracán": [
            { text: "¿En qué barrio de Buenos Aires se encuentra el equipo Huracán?", options: ["Parque Patricios", "La Boca", "Palermo"], correct: 0 },
            { text: "¿Cuál es el apodo de Huracán?", options: ["El Globo", "El Ciclón", "El Fortín"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Huracán?", options: ["Blanco y rojo", "Rojo y blanco", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Huracán?", options: ["Estadio Tomás Adolfo Ducó", "Estadio Diego Armando Maradona", "Estadio Nuevo Gasómetro"], correct: 0 },
            { text: "¿En qué año se fundó Huracán?", options: ["1908", "1909", "1910"], correct: 0 },
            { text: "¿Qué club es el clásico rival de Huracán?", options: ["San Lorenzo de Almagro", "Boca Juniors", "Independiente"], correct: 0 },
            { text: "¿Qué jugador es el máximo ídolo de Huracán?", options: ["Guillermo Stábile", "René Houseman", "Antonio Mohamed"], correct: 1 },
            { text: "¿Qué jugador de Huracán es conocido como 'El Patito'?", options: ["Patricio Toranzo", "Mariano Andújar", "Diego Mendoza"], correct: 0 },
            { text: "¿Cuál es el nombre del entrenador más exitoso en la historia de Huracán?", options: ["César Luis Menotti", "Ángel Cappa", "Miguel Brindisi"], correct: 0 },
            { text: "¿Cuál fue el logro más importante de Huracán en su historia?", options: ["Campeón de la Primera División", "Finalista de la Copa Sudamericana", "Ascenso a Primera División"], correct: 0 }
        ],
        "Independiente Rivadavia": [
            { text: "¿De qué provincia de Argentina es Independiente Rivadavia?", options: ["Mendoza", "San Juan", "La Rioja"], correct: 0 },
            { text: "¿Cuál es el apodo de Independiente Rivadavia?", options: ["La Lepra", "El Tomba", "La Academia"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Independiente Rivadavia?", options: ["Azul y blanco", "Rojo y blanco", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Independiente Rivadavia?", options: ["Estadio Bautista Gargantini", "Estadio Malvinas Argentinas", "Estadio Feliciano Gambarte"], correct: 0 },
            { text: "¿En qué año se fundó Independiente Rivadavia?", options: ["1913", "1915", "1919"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Independiente Rivadavia?", options: ["Godoy Cruz", "Gimnasia y Esgrima de Mendoza", "San Martín de Mendoza"], correct: 0 },
            { text: "¿Cuál fue el logro más importante de Independiente Rivadavia?", options: ["Ganar el Torneo Federal A", "Ascenso a la Primera Nacional", "Ascenso a la Primera División"], correct: 2 },
            { text: "¿Qué jugador es el máximo ídolo del club?", options: ["Rubén Forestello", "Adrián Fernández", "Sergio 'La Bestia' Sosa"], correct: 2 },
            { text: "¿En qué año Independiente Rivadavia ascendió por primera vez a Primera División?", options: ["1980", "2010", "2023"], correct: 2 },
            { text: "¿Qué otro equipo de Mendoza es su rival clásico?", options: ["Godoy Cruz", "San Martín de Mendoza", "Huracán Las Heras"], correct: 0 }
        ],
        "Instituto": [
            { text: "¿De qué provincia de Argentina es el equipo Instituto?", options: ["Córdoba", "Buenos Aires", "Santa Fe"], correct: 0 },
            { text: "¿Cuál es el apodo de Instituto?", options: ["La Gloria", "La Lepra", "El Pirata"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Instituto?", options: ["Rojo y blanco", "Blanco y negro", "Celeste y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Instituto?", options: ["Estadio Juan Domingo Perón", "Estadio Mario Alberto Kempes", "Estadio Julio César Villagra"], correct: 0 },
            { text: "¿En qué año se fundó el Club Instituto?", options: ["1914", "1918", "1923"], correct: 0 },
            { text: "¿Qué club es el clásico rival de Instituto?", options: ["Belgrano", "Talleres", "Racing de Córdoba"], correct: 2 },
            { text: "¿Qué jugador surgido de Instituto fue una estrella mundial?", options: ["Paulo Dybala", "Ángel Di María", "Gonzalo Higuaín"], correct: 0 },
            { text: "¿Qué otro jugador famoso del fútbol argentino surgió de Instituto?", options: ["Mario Alberto Kempes", "Lionel Messi", "Carlos Tevez"], correct: 0 },
            { text: "¿Cuál fue el mayor logro en la historia de Instituto?", options: ["Ganar la Primera Nacional", "Ascenso a Primera División", "Finalista de la Copa Argentina"], correct: 0 },
            { text: "¿En qué año Instituto regresó a la Primera División?", options: ["2020", "2022", "2023"], correct: 1 }
        ],
        "Lanús": [
            { text: "¿En qué localidad de la provincia de Buenos Aires se encuentra el equipo Lanús?", options: ["Lanús", "Lomas de Zamora", "Avellaneda"], correct: 0 },
            { text: "¿Cuál es el apodo de Lanús?", options: ["El Granate", "El Taladro", "El Verde"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Lanús?", options: ["Granate", "Rojo y blanco", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Lanús?", options: ["Estadio Ciudad de Lanús - Néstor Díaz Pérez", "Estadio Florencio Sola", "Estadio Juan Carmelo Zerillo"], correct: 0 },
            { text: "¿En qué año se fundó el Club Lanús?", options: ["1915", "1917", "1920"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Lanús?", options: ["Banfield", "Temperley", "Los Andes"], correct: 0 },
            { text: "¿Qué título internacional ganó Lanús en 2013?", options: ["Copa Libertadores", "Copa Sudamericana", "Recopa Sudamericana"], correct: 1 },
            { text: "¿Qué jugador de Lanús es conocido como 'Pepe'?", options: ["José Sand", "Lautaro Acosta", "Diego Valeri"], correct: 0 },
            { text: "¿Qué entrenador llevó a Lanús a ganar la Copa Sudamericana en 2013?", options: ["Guillermo Barros Schelotto", "Ramón Cabrero", "Luis Zubeldía"], correct: 0 },
            { text: "¿En qué año Lanús fue campeón de la Primera División?", options: ["2007", "2016", "2020"], correct: 1 }
        ],
        "Newell's Old Boys": [
            { text: "¿En qué ciudad de Argentina se encuentra el equipo Newell's Old Boys?", options: ["Rosario", "Santa Fe", "La Plata"], correct: 0 },
            { text: "¿Cuál es el apodo de Newell's Old Boys?", options: ["La Lepra", "El Canalla", "La Academia"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Newell's Old Boys?", options: ["Rojo y negro", "Rojo y blanco", "Azul y amarillo"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Newell's Old Boys?", options: ["Estadio Marcelo Bielsa", "Estadio Gigante de Arroyito", "Estadio Único de La Plata"], correct: 0 },
            { text: "¿En qué año se fundó Newell's Old Boys?", options: ["1903", "1905", "1910"], correct: 2 },
            { text: "¿Qué club es el clásico rival de Newell's Old Boys?", options: ["Rosario Central", "Unión", "Colón"], correct: 0 },
            { text: "¿Qué jugador famoso de la selección argentina surgió de Newell's Old Boys?", options: ["Lionel Messi", "Carlos Tevez", "Sergio Agüero"], correct: 0 },
            { text: "¿Qué entrenador es considerado un ídolo en Newell's Old Boys?", options: ["Marcelo Bielsa", "Gerardo Martino", "Gerardo Tata"], correct: 0 },
            { text: "¿Cuál fue el mayor logro internacional de Newell's Old Boys?", options: ["Finalista de la Copa Libertadores", "Campeón de la Copa Sudamericana", "Campeón de la Copa Conmebol"], correct: 0 },
            { text: "¿Qué jugador famoso de Newell's es conocido como 'El Tata'?", options: ["Gerardo Martino", "Maxi Rodríguez", "Ignacio Scocco"], correct: 0 }
        ],
        "Platense": [
            { text: "¿En qué barrio de Buenos Aires se encuentra el equipo Platense?", options: ["Vicente López", "Saavedra", "Núñez"], correct: 0 },
            { text: "¿Cuál es el apodo de Platense?", options: ["El Calamar", "El Canalla", "El Funebrero"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Platense?", options: ["Blanco y marrón", "Azul y blanco", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Platense?", options: ["Estadio Ciudad de Vicente López", "Estadio Islas Malvinas", "Estadio Don León Kolbowski"], correct: 0 },
            { text: "¿En qué año se fundó el Club Platense?", options: ["1905", "1908", "1910"], correct: 0 },
            { text: "¿Qué club es el clásico rival de Platense?", options: ["Tigre", "Chacarita Juniors", "Argentinos Juniors"], correct: 0 },
            { text: "¿Cuál fue el mayor logro de Platense en su historia?", options: ["Campeón de la Primera B Nacional", "Ascenso a la Primera División", "Finalista de la Copa Argentina"], correct: 1 },
            { text: "¿Qué jugador surgido de Platense jugó en la selección argentina?", options: ["David Trezeguet", "Juan Román Riquelme", "Roberto Perfumo"], correct: 0 },
            { text: "¿En qué año Platense regresó a la Primera División?", options: ["2018", "2021", "2023"], correct: 1 },
            { text: "¿Qué ex jugador de Platense es conocido como 'El Burrito'?", options: ["Roberto Perfumo", "Diego Armando Maradona", "Ariel Aranda"], correct: 2 }
        ],
        "Rosario Central": [
            { text: "¿En qué ciudad de Argentina se encuentra el equipo Rosario Central?", options: ["Rosario", "Santa Fe", "Córdoba"], correct: 0 },
            { text: "¿Cuál es el apodo de Rosario Central?", options: ["El Canalla", "La Lepra", "El Matador"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Rosario Central?", options: ["Azul y amarillo", "Rojo y negro", "Celeste y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Rosario Central?", options: ["Estadio Gigante de Arroyito", "Estadio Marcelo Bielsa", "Estadio Brigadier General Estanislao López"], correct: 0 },
            { text: "¿En qué año se fundó Rosario Central?", options: ["1889", "1893", "1903"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Rosario Central?", options: ["Newell's Old Boys", "Unión", "Colón"], correct: 0 },
            { text: "¿Qué título internacional ganó Rosario Central?", options: ["Copa Libertadores", "Copa Sudamericana", "Copa Conmebol"], correct: 2 },
            { text: "¿Qué jugador de Rosario Central es conocido como 'El Flaco'?", options: ["Ángel Di María", "Mario Alberto Kempes", "César Delgado"], correct: 0 },
            { text: "¿Quién fue el entrenador que llevó a Rosario Central a ganar la Copa Argentina en 2018?", options: ["Eduardo Coudet", "Pablo Lavallén", "Diego Cocca"], correct: 1 },
            { text: "¿En qué año Rosario Central ganó su único título internacional?", options: ["1995", "1996", "1997"], correct: 0 }
        ],
        "San Lorenzo de Almagro": [
            { text: "¿En qué barrio de Buenos Aires se encuentra el equipo San Lorenzo de Almagro?", options: ["Boedo", "La Boca", "Parque Patricios"], correct: 0 },
            { text: "¿Cuál es el apodo de San Lorenzo de Almagro?", options: ["El Ciclón", "El Globo", "El Cuervo"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de San Lorenzo de Almagro?", options: ["Rojo y azul", "Rojo y blanco", "Azul y amarillo"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de San Lorenzo de Almagro?", options: ["Estadio Nuevo Gasómetro", "Estadio Pedro Bidegain", "Estadio José Amalfitani"], correct: 0 },
            { text: "¿En qué año se fundó San Lorenzo de Almagro?", options: ["1908", "1909", "1910"], correct: 0 },
            { text: "¿Qué club es el clásico rival de San Lorenzo de Almagro?", options: ["Huracán", "Boca Juniors", "River Plate"], correct: 0 },
            { text: "¿Qué título internacional ganó San Lorenzo de Almagro en 2014?", options: ["Copa Sudamericana", "Copa Libertadores", "Recopa Sudamericana"], correct: 1 },
            { text: "¿Qué jugador de San Lorenzo es conocido como 'Pipi'?", options: ["Leandro Romagnoli", "Néstor Ortigoza", "Juan Mercier"], correct: 0 },
            { text: "¿Quién fue el entrenador que llevó a San Lorenzo a ganar la Copa Libertadores?", options: ["Edgardo Bauza", "Ramón Díaz", "Diego Aguirre"], correct: 0 },
            { text: "¿Cuál es el nombre del proyecto de San Lorenzo para volver a su estadio original?", options: ["La vuelta a Boedo", "Volver a casa", "El regreso a Almagro"], correct: 0 }
        ],
        "San Martín de San Juan": [
            { text: "¿De qué provincia de Argentina es el equipo San Martín de San Juan?", options: ["San Juan", "Mendoza", "San Luis"], correct: 0 },
            { text: "¿Cuál es el apodo de San Martín de San Juan?", options: ["El Verdinegro", "El Ciclón", "El Tomba"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de San Martín de San Juan?", options: ["Verde y negro", "Rojo y blanco", "Blanco y azul"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de San Martín de San Juan?", options: ["Estadio Ingeniero Hilario Sánchez", "Estadio Bicentenario", "Estadio Malvinas Argentinas"], correct: 0 },
            { text: "¿En qué año se fundó San Martín de San Juan?", options: ["1907", "1908", "1909"], correct: 0 },
            { text: "¿Qué club es el clásico rival de San Martín de San Juan?", options: ["Godoy Cruz", "Independiente Rivadavia", "Atlético San Martín"], correct: 2 },
            { text: "¿En qué año San Martín de San Juan logró su primer ascenso a la Primera División?", options: ["1967", "1972", "2007"], correct: 2 },
            { text: "¿Qué jugador es el máximo ídolo del club?", options: ["Emanuel Mas", "Claudio Graf", "Mauro Icardi"], correct: 1 },
            { text: "¿Qué jugador surgido de las inferiores de San Martín de San Juan jugó en la selección argentina?", options: ["Emanuel Mas", "Carlos Tévez", "Lionel Messi"], correct: 0 },
            { text: "¿Cuál fue el mayor logro en la historia de San Martín de San Juan?", options: ["Ascenso a Primera División", "Finalista de la Copa Argentina", "Campeón de la Primera Nacional"], correct: 0 }
        ],
        "Sarmiento": [
            { text: "¿De qué localidad de la provincia de Buenos Aires es el equipo Sarmiento?", options: ["Junín", "La Plata", "Mar del Plata"], correct: 0 },
            { text: "¿Cuál es el apodo de Sarmiento?", options: ["El Verde", "El Canalla", "El Guapo"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Sarmiento?", options: ["Verde y blanco", "Rojo y blanco", "Azul y oro"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Sarmiento?", options: ["Estadio Eva Perón", "Estadio Mario Alberto Kempes", "Estadio Florencio Sola"], correct: 0 },
            { text: "¿En qué año se fundó el Club Sarmiento?", options: ["1911", "1912", "1914"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Sarmiento?", options: ["Jorge Newbery", "Chacarita Juniors", "Platense"], correct: 0 },
            { text: "¿En qué año Sarmiento logró su primer ascenso a la Primera División?", options: ["1970", "1981", "2015"], correct: 1 },
            { text: "¿Qué jugador surgido de las inferiores de Sarmiento fue un destacado delantero en el fútbol argentino?", options: ["José Francisco Sanfilippo", "Ricardo Gareca", "Carlos Bueno"], correct: 0 },
            { text: "¿En qué año Sarmiento volvió a ascender a Primera División?", options: ["2014", "2020", "2021"], correct: 2 },
            { text: "¿Cuál fue el mayor logro en la historia de Sarmiento?", options: ["Campeón de la Primera Nacional", "Ascenso a Primera División", "Finalista de la Copa Argentina"], correct: 0 }
        ],
        "Talleres": [
            { text: "¿De qué provincia de Argentina es el equipo Talleres?", options: ["Córdoba", "Buenos Aires", "Santa Fe"], correct: 0 },
            { text: "¿Cuál es el apodo de Talleres?", options: ["La T", "El Matador", "El Pirata"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Talleres?", options: ["Azul y blanco", "Rojo y negro", "Celeste y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Talleres?", options: ["Estadio Mario Alberto Kempes", "Estadio Juan Carmelo Zerillo", "Estadio Julio César Villagra"], correct: 0 },
            { text: "¿En qué año se fundó el Club Talleres?", options: ["1911", "1913", "1915"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Talleres?", options: ["Belgrano", "Instituto", "Racing de Córdoba"], correct: 0 },
            { text: "¿Qué título internacional ganó Talleres?", options: ["Copa Conmebol", "Copa Sudamericana", "Copa Libertadores"], correct: 0 },
            { text: "¿Qué jugador es el máximo ídolo en la historia de Talleres?", options: ["Luis Galván", "Daniel Valencia", "Luis 'El Loco' Herrera"], correct: 2 },
            { text: "¿Quién fue el entrenador que llevó a Talleres a ganar la Copa Conmebol en 1999?", options: ["Ricardo Gareca", "Juan José López", "Ricardo Lavolpe"], correct: 0 },
            { text: "¿En qué año Talleres volvió a la Primera División?", options: ["2014", "2016", "2018"], correct: 1 }
        ],
        "Tigre": [
            { text: "¿En qué localidad de la provincia de Buenos Aires se encuentra el equipo Tigre?", options: ["Victoria", "Tigre", "San Fernando"], correct: 0 },
            { text: "¿Cuál es el apodo de Tigre?", options: ["El Matador", "El Calamar", "El Pincha"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Tigre?", options: ["Azul y rojo", "Rojo y blanco", "Verde y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Tigre?", options: ["Estadio José Dellagiovanna", "Estadio Monumental", "Estadio Ciudad de Vicente López"], correct: 0 },
            { text: "¿En qué año se fundó el Club Tigre?", options: ["1902", "1905", "1908"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Tigre?", options: ["Platense", "Atlanta", "Chacarita Juniors"], correct: 0 },
            { text: "¿Qué título oficial ganó Tigre en 2019?", options: ["Copa Superliga Argentina", "Copa Argentina", "Primera Nacional"], correct: 0 },
            { text: "¿Qué jugador surgido de las inferiores de Tigre es un destacado delantero en el fútbol argentino?", options: ["Martín Galmarini", "Lucas Pratto", "Pablo Vitti"], correct: 1 },
            { text: "¿En qué año Tigre fue subcampeón de la Copa Sudamericana?", options: ["2010", "2012", "2014"], correct: 1 },
            { text: "¿Quién es el máximo ídolo de Tigre?", options: ["Carlos Luna", "Martín Galmarini", "Diego Castaño"], correct: 0 }
        ],
        "Unión": [
            { text: "¿En qué provincia de Argentina se encuentra el equipo Unión?", options: ["Santa Fe", "Córdoba", "Buenos Aires"], correct: 0 },
            { text: "¿Cuál es el apodo de Unión?", options: ["El Tatengue", "El Sabalero", "El Canalla"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Unión?", options: ["Rojo y blanco", "Negro y rojo", "Celeste y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Unión?", options: ["Estadio 15 de Abril", "Estadio Brigadier General Estanislao López", "Estadio 23 de Agosto"], correct: 0 },
            { text: "¿En qué año se fundó el Club Unión?", options: ["1905", "1907", "1910"], correct: 1 },
            { text: "¿Qué club es el clásico rival de Unión?", options: ["Colón", "Gimnasia y Esgrima", "Rosario Central"], correct: 0 },
            { text: "¿Qué jugador histórico de la selección argentina jugó en Unión?", options: ["Leopoldo Luque", "Nery Pumpido", "Pedro Pasculli"], correct: 0 },
            { text: "¿Cuál fue el logro más importante de Unión en su historia?", options: ["Ganar un torneo de Primera División", "Ascenso a Primera División", "Finalista de la Copa Argentina"], correct: 1 },
            { text: "¿Qué jugador de Unión es conocido como 'El Tanque'?", options: ["Nery Pumpido", "Claudio Ubeda", "Nereo Fernández"], correct: 0 },
            { text: "¿En qué año Unión ascendió a la Primera División?", options: ["1974", "1989", "1996"], correct: 0 }
        ],
        "Vélez Sarsfield": [
            { text: "¿En qué barrio de Buenos Aires se encuentra el equipo Vélez Sarsfield?", options: ["Liniers", "Caballito", "Flores"], correct: 0 },
            { text: "¿Cuál es el apodo de Vélez Sarsfield?", options: ["El Fortín", "El Trico", "El Calamar"], correct: 0 },
            { text: "¿Qué colores predominan en la camiseta de Vélez Sarsfield?", options: ["Blanco con una V azul", "Azul y blanco", "Rojo y blanco"], correct: 0 },
            { text: "¿Cuál es el nombre del estadio de Vélez Sarsfield?", options: ["Estadio José Amalfitani", "Estadio Nuevo Gasómetro", "Estadio Malvinas Argentinas"], correct: 0 },
            { text: "¿En qué año se fundó Vélez Sarsfield?", options: ["1910", "1915", "1920"], correct: 0 },
            { text: "¿Qué club es el clásico rival de Vélez Sarsfield?", options: ["Ferro Carril Oeste", "Argentinos Juniors", "Huracán"], correct: 0 },
            { text: "¿Qué título internacional ganó Vélez Sarsfield en 1994?", options: ["Copa Sudamericana", "Copa Intercontinental", "Recopa Sudamericana"], correct: 1 },
            { text: "¿Qué entrenador llevó a Vélez Sarsfield a ganar la Copa Libertadores y la Intercontinental en 1994?", options: ["Carlos Bianchi", "José Pekerman", "Marcelo Bielsa"], correct: 0 },
            { text: "¿Qué jugador surgido de Vélez Sarsfield es conocido como 'El Tanque'?", options: ["Mauro Zárate", "Lucas Pratto", "Santiago Silva"], correct: 2 },
            { text: "¿Cuál es el nombre del ex-jugador y entrenador que es ídolo en Vélez Sarsfield?", options: ["Carlos Ischia", "Ricardo Gareca", "Omar Asad"], correct: 1 }
        ]
    }
};
